### ISSUE TITLE
[Bug] WorkerProc failed to start after upgrading flag_gems to 4.2.1rc0: AttributeError: module 'triton.language.math' has no attribute 'acos'

### ISSUE THREAD

**Issue by buzhengjing** [flagos-ai/FlagGems#1687]
### Describe the bug

🐛 Describe the bug
After upgrading flag_gems from version 4.2.0 to 4.2.1rc0, the vLLM Ascend service fails to start. The worker process crashes during initialization with an AttributeError indicating that triton.language.math does not have the acos attribute.
The error occurs when vllm_ascend attempts to import NPUModelRunner, which subsequently imports flag_gems.
🔄 Reproduction Steps
1. Start with a working environment using:
  - flag_gems: 4.2.0
  - vllm: 0.13.0+empty (vllm-ascend fork)
  - flagtree: 0.4.0+ascend3.2
2. Upgrade flag_gems to 4.2.1rc0 (commit 34fb9857bb15024b144f982c539468763ec7ea8c).
3. Attempt to start the vLLM server (e.g., vllm serve ...).
4. Observe the WorkerProc failed to start error.
📄 Error Logs
text
编辑
ERROR 02-25 17:29:05 [multiproc_executor.py:751] WorkerProc failed to start.
...
File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 21, in <module>
  import flag_gems
File "/usr/local/python3.11.13/lib/python3.11/site-packages/flag_gems/__init__.py", line 10, in <module>
  from flag_gems.fused import *  # noqa: F403
...
File "/usr/local/python3.11.13/lib/python3.11/site-packages/flag_gems/ops/acos.py", line 8, in <module>
  _acos = tl_extra_shim.acos
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'triton.language.math' has no attribute 'acos'
...
RuntimeError: Engine core initialization failed. See root cause above.
🖥️ Environment Info
- OS: Linux (Ascend Environment)
- Python Version: 3.11.13
- CANN Version: (Please fill in your CANN version, e.g., 8.0.RC1)
- Hardware: (e.g., Ascend 910B)
Package Versions (Before Upgrade - Working):
- flag_gems: 4.2.0
- flag_scale: 1.0.0
- flagtree: 0.4.0+ascend3.2
- vllm: 0.13.0+empty
- triton: (Please run pip show triton and fill in the version, e.g., 2.1.0 or custom build)
Package Versions (After Upgrade - Failing):
- flag_gems: 4.2.1rc0 (commit: 34fb9857bb15024b144f982c539468763ec7ea8c)
- triton: (Same as above)
💡 Additional Context
- The error suggests that flag_gems 4.2.1rc0 now relies on triton.language.math.acos, which is not present in the currently installed triton version.
- Did the minimum required triton version change in flag_gems 4.2.1rc0?
- Is there a specific triton version (or commit) compatible with flag_gems 4.2.1rc0 for Ascend environments?
- Rolling back to flag_gems 4.2.0 resolves the issue immediately.
✅ Checklist
- I have searched existing issues to ensure this bug has not been reported.
- I have verified the error occurs consistently after the upgrade.
- I have confirmed that rolling back the package fixes the issue.
